# array数组的数值计算

In [1]:
import numpy as np

### 1、求和（numpy模块函数/array数组方法）

In [2]:
tang_array = np.array([[1,2,3],[4,5,6]])
tang_array

array([[1, 2, 3],
       [4, 5, 6]])

In [3]:
np.sum(tang_array)

21

#### 指定要进行的操作是沿着什么轴,0是沿纵轴，1是沿横轴

In [4]:
np.sum(tang_array, axis = 0)

array([5, 7, 9])

In [5]:
tang_array.ndim

2

In [6]:
np.sum(tang_array, axis = 1)

array([ 6, 15])

In [7]:
np.sum(tang_array, axis = -1)

array([ 6, 15])

In [8]:
tang_array.sum()

21

In [9]:
tang_array.sum(axis = 1)

array([ 6, 15])

In [10]:
tang_array.sum(axis = 0)

array([5, 7, 9])

### 2、求积

In [11]:
tang_array.prod()

720

In [12]:
tang_array.prod(axis = 0)

array([ 4, 10, 18])

### 3、求最大值最小值（索引）

In [13]:
tang_array.min()

1

In [14]:
tang_array.max()

6

In [15]:
tang_array.max(axis = 0)

array([4, 5, 6])

In [16]:
tang_array.max(1)

array([3, 6])

In [17]:
tang_array.argmin()

0

In [18]:
tang_array.argmin(axis = 0)

array([0, 0, 0], dtype=int64)

In [19]:
tang_array.argmax(axis = 0)

array([1, 1, 1], dtype=int64)

### 4、平均值

In [20]:
tang_array.mean()

3.5

### 5、标准差的计算

In [21]:
tang_array.std()

1.707825127659933

### 6、方差的计算

In [22]:
tang_array.std(axis = 0)

array([1.5, 1.5, 1.5])

### 7、做限制,小于2的值都变成2，大于3的值都变成3

In [23]:
tang_array.clip(2,3)

array([[2, 2, 3],
       [3, 3, 3]])

### 8、四舍五入,decimals是四舍五入的精度

In [24]:
tang_array = np.array([1,2,4.3,4.5])

In [25]:
tang_array.round(decimals = 0)

array([1., 2., 4., 4.])