In [1]:
import numpy as np

In [2]:
tang_array = np.arange(10)

In [3]:
tang_array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
tang_array.shape

(10,)

In [5]:
tang_array.shape = (2, 5)

In [6]:
tang_array

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [7]:
tang_array.shape = 5,2

改变数组形状时大小不能改变

In [10]:
tang_array

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [11]:
tang_array.reshape(1,10)

array([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [12]:
tang_array = np.arange(10)

In [13]:
tang_array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [14]:
tang_array = tang_array[:,np.newaxis]

压缩操作，去除所有空的轴

In [17]:
tang_array.squeeze()

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [22]:
tang_array.shape = 2,5
tang_array

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

数组的转置

In [19]:
tang_array.transpose()

array([[0, 5],
       [1, 6],
       [2, 7],
       [3, 8],
       [4, 9]])

In [21]:
tang_array.T

array([[0, 5],
       [1, 6],
       [2, 7],
       [3, 8],
       [4, 9]])

数组的连接

In [24]:
a  = np.array([[1,2,3],[2,3,4]])
a

array([[1, 2, 3],
       [2, 3, 4]])

In [25]:
b  = np.array([[22,3,43],[32,352,45]])
b

array([[ 22,   3,  43],
       [ 32, 352,  45]])

In [27]:
c = np.concatenate((a, b))

In [28]:
c

array([[  1,   2,   3],
       [  2,   3,   4],
       [ 22,   3,  43],
       [ 32, 352,  45]])

In [29]:
c = np.concatenate((a, b), axis = 1)

In [30]:
c

array([[  1,   2,   3,  22,   3,  43],
       [  2,   3,   4,  32, 352,  45]])

In [31]:
np.vstack((a,b))   #竖着连接

array([[  1,   2,   3],
       [  2,   3,   4],
       [ 22,   3,  43],
       [ 32, 352,  45]])

In [32]:
np.hstack((a,b))    #横着连接

array([[  1,   2,   3,  22,   3,  43],
       [  2,   3,   4,  32, 352,  45]])

In [33]:
a

array([[1, 2, 3],
       [2, 3, 4]])

拉平操作,不会改变原数组

In [34]:
a.flatten()

array([1, 2, 3, 2, 3, 4])

In [36]:
a.ravel()

array([1, 2, 3, 2, 3, 4])

In [37]:
a

array([[1, 2, 3],
       [2, 3, 4]])