# 数组生成

In [1]:
import numpy as np

### 1、arange(左开，右闭，步长，类型）

In [2]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [3]:
np.arange(1,11,2)

array([1, 3, 5, 7, 9])

In [4]:
np.arange(2,20,2,dtype = np.float32)

array([ 2.,  4.,  6.,  8., 10., 12., 14., 16., 18.], dtype=float32)

### 2、linespace(左开，右闭，多少个数），构造等距分布，包含头尾

In [5]:
np.linspace(0,10,10)

array([ 0.        ,  1.11111111,  2.22222222,  3.33333333,  4.44444444,
        5.55555556,  6.66666667,  7.77777778,  8.88888889, 10.        ])

In [6]:
np.logspace(0,1,5)    #以10为底的指数分布

array([ 1.        ,  1.77827941,  3.16227766,  5.62341325, 10.        ])

### 3、坐标矩阵

In [7]:
x = np.linspace(-10, 10, 5)
x

array([-10.,  -5.,   0.,   5.,  10.])

In [8]:
y = np.linspace(-10, 10, 5)
y

array([-10.,  -5.,   0.,   5.,  10.])

In [9]:
x,y=np.meshgrid(x,y)

In [10]:
x

array([[-10.,  -5.,   0.,   5.,  10.],
       [-10.,  -5.,   0.,   5.,  10.],
       [-10.,  -5.,   0.,   5.,  10.],
       [-10.,  -5.,   0.,   5.,  10.],
       [-10.,  -5.,   0.,   5.,  10.]])

In [11]:
y

array([[-10., -10., -10., -10., -10.],
       [ -5.,  -5.,  -5.,  -5.,  -5.],
       [  0.,   0.,   0.,   0.,   0.],
       [  5.,   5.,   5.,   5.,   5.],
       [ 10.,  10.,  10.,  10.,  10.]])

### 4、np.r_是按列连接两个矩阵，就是把两矩阵上下相加，要求列数相等。
### np.c_是按行连接两个矩阵，就是把两矩阵左右相加，要求行数相等。

In [12]:
np.r_[:10]

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [13]:
np.c_[:10]

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

### 5、更常用的zeros ones，参数为形状数组

In [14]:
np.zeros(3)

array([0., 0., 0.])

In [15]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [16]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [17]:
np.ones((3, 3), dtype = np.int32) * 8

array([[8, 8, 8],
       [8, 8, 8],
       [8, 8, 8]])

### 6、empty开辟随机数组空间，后用fill方法填充数值

In [18]:
x = np.empty(5)
x

array([2.12199579e-314, 6.36598737e-314, 1.06099790e-313, 1.48539705e-313,
       1.90979621e-313])

In [19]:
x.fill(1)
x

array([1., 1., 1., 1., 1.])

### 7、输入为矩阵x、输出为形状和x一致的矩阵，其元素全部为0或1

In [20]:
np.zeros_like(x)

array([0., 0., 0., 0., 0.])

In [21]:
np.ones_like(x)

array([1., 1., 1., 1., 1.])

### 8、单位矩阵

In [22]:
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])