In [1]:
import numpy as np

In [2]:
array = [1,2,3,4,5]

In [3]:
array

[1, 2, 3, 4, 5]

#### 用数组初始化array

In [4]:
array = np.array([1,2,3,4,5])

In [5]:
array

array([1, 2, 3, 4, 5])

#### array的运算具有广播性

In [18]:
array+=1

In [7]:
type(array)

numpy.ndarray

In [8]:
array

array([2, 3, 4, 5, 6])

In [9]:
array2 = array + 1

In [10]:
array2

array([3, 4, 5, 6, 7])

#### 数组间的运算，数组必须具有同样的shape

In [11]:
array2 + array

array([ 5,  7,  9, 11, 13])

In [12]:
array2 * array

array([ 6, 12, 20, 30, 42])

#### array支持下标索引

In [13]:
array[2]

4

#### array支持切片操作

In [14]:
array[:2]

array([2, 3])

#### array的形状

In [15]:
array.shape

(5,)

#### 二维数组

In [16]:
np.array([[1,2,3],[2,3,3]])

array([[1, 2, 3],
       [2, 3, 3]])

In [17]:
np.array([[1,2,3],[2,3,3]]).shape

(2, 3)