In [1]:
import numpy as np

#### 1、打印当前Numpy版本

In [2]:
print(np.__version__)

1.21.5


#### 2、构造一个全零的矩阵，并打印其占用的内存大小

In [3]:
cheng_array = np.zeros((3,3), dtype = np.int32)
cheng_array

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [4]:
cheng_array.nbytes

36

In [5]:
cheng_array.size * cheng_array.itemsize

36

#### 3、打印一个帮助文档

In [6]:
print(help(np.info(np.add)))

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out

#### 4、倒序排列

In [7]:
np.arange(10,50)[::-1]

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10])

#### 5、找到数组中不为0的索引

In [8]:
np.nonzero([1,2,3,4,0,0,5,0])

(array([0, 1, 2, 3, 6], dtype=int64),)

#### 6、随机构造3*3的矩阵，打印最大值和最小值

In [9]:
array = np.random.rand(3,3)
array

array([[0.05123293, 0.37014506, 0.50490946],
       [0.15798787, 0.06185318, 0.110416  ],
       [0.33635457, 0.29456482, 0.55140777]])

In [10]:
array.max()

0.5514077739463936

In [11]:
array.min()

0.05123293120817074

#### 7、构造5*5的矩阵，并在最外层加上一圈0，np.pad方法

In [12]:
array2 = np.ones((5,5))
array2

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [13]:
array2 = np.pad(array2, pad_width= 1,mode = 'constant', constant_values = 0)

In [14]:
array2

array([[0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0.]])

#### 8、构建一个shape为 (6, 7, 8)的矩阵，并找到第100个元素的索引值

In [15]:
array3 = np.random.rand(6,7,8)
array3

array([[[4.01147115e-01, 3.48168475e-01, 2.09858649e-01, 4.44446395e-01,
         6.74035633e-01, 8.54293141e-01, 8.29281353e-01, 8.75400221e-03],
        [1.03846767e-01, 7.63536346e-02, 7.86069872e-01, 3.86863150e-01,
         4.74241811e-01, 3.96307340e-01, 8.58414848e-01, 7.51321839e-01],
        [6.87195711e-01, 2.16294987e-01, 6.34155821e-01, 8.95246006e-01,
         5.92755384e-01, 9.75829825e-01, 4.55529204e-01, 1.85362684e-01],
        [1.76356363e-01, 2.14064196e-01, 6.89618893e-01, 9.97292587e-01,
         8.56872394e-01, 1.62673861e-01, 8.77453477e-02, 2.33544910e-01],
        [2.25285491e-01, 4.90829047e-01, 8.07889521e-01, 7.12566310e-01,
         3.72758861e-02, 9.91754818e-01, 4.68017429e-01, 7.60098255e-02],
        [8.18163177e-01, 9.17595722e-01, 7.55271662e-01, 9.53859748e-01,
         4.59764811e-01, 7.94576894e-01, 5.60750648e-01, 4.06073593e-01],
        [2.96765328e-01, 1.45523679e-01, 2.78559869e-01, 9.55852131e-01,
         9.13275714e-01, 7.51115130e-01, 6.11

In [16]:
np.unravel_index(100,array3.shape)

(1, 5, 4)

#### 9、对一个5*5的矩阵做归一化操作

In [17]:
array4 = np.random.rand(5,5)

In [18]:
aMax = array4.max()
aMin = array4.min()
array4 = (array4 - aMin / aMax - aMin)

In [19]:
array4

array([[ 0.07894005,  0.31143464,  0.85467513,  0.26555355, -0.07022548],
       [ 0.6766214 ,  0.77857071,  0.31881094,  0.34433654,  0.32347474],
       [ 0.67394723,  0.02623328,  0.42415824,  0.55536888,  0.63865299],
       [ 0.29118826,  0.82686131,  0.20619058,  0.61252977, -0.0132297 ],
       [ 0.35765988,  0.55651824,  0.43221497,  0.05933323,  0.08904795]])

#### 10、找到两个数组中相同的值

In [20]:
array1 = np.random.randint(0,10,10)

In [21]:
array2 = np.random.randint(0,10,10)

In [22]:
np.intersect1d(array1, array2)

array([2, 8])

In [23]:
print(array1)
print(array2)

[1 1 6 9 0 0 8 1 9 2]
[8 2 2 2 5 4 8 8 2 7]


#### 11、得到今天 明天 昨天的日期

In [24]:
yesterday = np.datetime64('today','D') - np.timedelta64(1, 'D')
today = np.datetime64('today','D')
tommorow = np.datetime64('today', 'D') + np.timedelta64(1, 'D')
today

numpy.datetime64('2022-09-12')

In [25]:
yesterday

numpy.datetime64('2022-09-11')

In [26]:
tommorow

numpy.datetime64('2022-09-13')

#### 12、得到一个月中的所有天

In [27]:
#np.arange('2022-7', '2020-8',dtype = 'datetime64[D]')

#### 13、得到一个数的整数部分

In [28]:
z = np.random.uniform(0, 10, 10)

In [29]:
z

array([4.05556599, 1.36890116, 1.36179028, 0.4804507 , 2.22066978,
       4.71152027, 3.75141196, 3.06336869, 4.37084996, 8.98878642])

In [30]:
np.floor(z)

array([4., 1., 1., 0., 2., 4., 3., 3., 4., 8.])

In [31]:
z-np.floor(z)

array([0.05556599, 0.36890116, 0.36179028, 0.4804507 , 0.22066978,
       0.71152027, 0.75141196, 0.06336869, 0.37084996, 0.98878642])

#### 14、构造一个数组，让他不能被改变

In [32]:
array5 = np.random.rand(5,5)

In [33]:
array5.flags.writeable = False

In [34]:
array5

array([[3.83849943e-01, 4.11931311e-01, 2.27989130e-01, 9.99044578e-01,
        2.79332919e-01],
       [8.95159722e-01, 5.85029048e-01, 7.57653571e-01, 6.93021819e-01,
        8.90376726e-01],
       [1.00158811e-01, 3.46330253e-01, 1.59532363e-01, 3.76145141e-01,
        2.87448903e-01],
       [5.98650043e-01, 2.66560364e-01, 7.44966862e-01, 3.76991734e-04,
        1.66649735e-01],
       [7.88879831e-01, 4.61172632e-01, 1.59280592e-01, 8.23019703e-02,
        8.75252285e-01]])

In [35]:
array5[1] = 1

ValueError: assignment destination is read-only

#### 15、打印大数据的部分值，全部值

In [36]:
array6 = np.zeros((150,150))
array6

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [37]:
np.set_printoptions( threshold = 10 )

In [38]:
array6

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

#### 16、找到一个数组中，最接近一个数的索引

In [39]:
array6 = np.arange(100)

In [41]:
v = np.random.uniform(0,100)
v

17.43815636606293

In [42]:
index = (np.abs(array6 - v)).argmin()
array6[index]

17

#### 17、32float类型和32位int类型转换

In [43]:
array7 = np.arange(10, dtype = np.int32)

In [44]:
array7.dtype

dtype('int32')

In [45]:
array7 = array7.astype(np.float32)

In [46]:
array7.dtype

dtype('float32')

#### 18、打印数组元素位置与数值,np.ndenumerate(array)

In [47]:
array8 = np.arange(9).reshape(3,3)
array8

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [48]:
for index,value in np.ndenumerate(array8):
    print(index,value)

(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8


#### 19、按照数组的某一列进行排序

In [50]:
array9 = np.random.randint(0,10,(3,3))
array9

array([[3, 1, 5],
       [3, 4, 7],
       [9, 3, 7]])

In [51]:
array9[:,1].sort()

In [52]:
array9

array([[3, 1, 5],
       [3, 3, 7],
       [9, 4, 7]])

#### 20、统计数组中每个值出现的次数

In [53]:
z = np.random.randint(0,10,10)

In [54]:
np.bincount(z)

array([1, 2, 0, 0, 1, 1, 1, 3, 0, 1], dtype=int64)

#### 21、对一个四维数组最后两维进行求和

In [55]:
z = np.random.randint(0,10,(5,5,5,5))
res = z.sum(axis = (-2,-1))
res

array([[109, 132, 107, 112, 102],
       [ 95, 121, 101, 131, 122],
       [117, 134, 140, 125, 113],
       [135, 101, 122, 104, 131],
       [123, 125, 109, 112, 100]])

#### 22、交换矩阵的两行

In [56]:
z = np.arange(25).reshape(5,5)
z

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [57]:
z[0,1]=z[1,0]

In [58]:
z

array([[ 0,  5,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

#### 23、找到一个数组中最常出现的数字

In [59]:
z = np.random.randint(0,50,50)

In [60]:
np.bincount(z).argmax()

19

#### 24、快速查找

In [68]:
z = np.arange(10000)
np.random.shuffle(z)

In [62]:
z[np.argpartition(-z,5)[:5]]

array([9998, 9999, 9997, 9995, 9996])

#### 25、去除掉数组中，所有元素都相同的数据

In [63]:
np.set_printoptions(threshold=np.inf)
z = np.random.randint(0,3,(10,3))
z

array([[2, 1, 1],
       [0, 2, 1],
       [1, 2, 0],
       [2, 0, 0],
       [1, 0, 1],
       [0, 2, 0],
       [1, 0, 1],
       [1, 1, 0],
       [2, 2, 2],
       [2, 0, 2]])

In [65]:
z[:,1:]

array([[1, 1],
       [2, 1],
       [2, 0],
       [0, 0],
       [0, 1],
       [2, 0],
       [0, 1],
       [1, 0],
       [2, 2],
       [0, 2]])

In [64]:
np.all(z[:,:-1] == z[:,1:],axis =1 )

array([False, False, False, False, False, False, False, False,  True,
       False])