# array结构

In [1]:
import numpy as np

#### 对于ndarray结构来说，里面所有的元素必须是同一类型的，如果不是的话，会自动向下进行转换

In [2]:
tang_list= [1,2,3,4,5.0]
tang_array = np.array(tang_list)

In [3]:
tang_array

array([1., 2., 3., 4., 5.])

### 基本属性操作

#### 1、元素类型

In [4]:
tang_array.dtype               #必须是相同类型，不同类型会自动向下转换

dtype('float64')

#### 2、元素占内存大小

In [5]:
tang_array.itemsize 

8

#### 3、数组形状

In [6]:
tang_array.shape

(5,)

#### 4、数组元素个数（数组属性/numpy方法）

In [7]:
tang_array.size

5

In [8]:
np.size(tang_array)

5

In [9]:
from numpy import size

In [10]:
size(tang_array)

5

#### 5、数组的维数

In [11]:
tang_array.ndim

1

In [12]:
tang_array

array([1., 2., 3., 4., 5.])

#### 6、用0填充数组

In [13]:
tang_array.fill(0)

In [14]:
tang_array

array([0., 0., 0., 0., 0.])

#### 7、索引与切片,跟python都是一样的

In [15]:
tang_list= [1,2,3,4,5.0]
tang_array = np.array(tang_list)

In [16]:
tang_array[2]

3.0

In [17]:
tang_array[:3]

array([1., 2., 3.])

#### 8、矩阵格式

In [18]:
tang_array = np.array([[1,2,3],
                      [4,5,6],
                      [7,8,9]])

In [19]:
tang_array

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [20]:
tang_array.shape

(3, 3)

In [21]:
tang_array.size

9

In [22]:
tang_array.ndim

2

#### 9、二维数组的索引

In [23]:
tang_array[1,1]

5

In [24]:
tang_array[2,2]

9

#### 10、修改数组中的值

In [25]:
tang_array[1,1] = 10

In [26]:
tang_array

array([[ 1,  2,  3],
       [ 4, 10,  6],
       [ 7,  8,  9]])

In [27]:
tang_array[1] #矩阵第二行

array([ 4, 10,  6])

In [28]:
tang_array[:,1] #矩阵第二列

array([ 2, 10,  8])

In [29]:
tang_array2 = tang_array

In [30]:
tang_array2[1,1] = 100

In [31]:
tang_array

array([[  1,   2,   3],
       [  4, 100,   6],
       [  7,   8,   9]])

#### 11、复制一个副本，在副本上的操作不会修改原数组的值

In [32]:
tang_array2 = tang_array.copy()

In [33]:
tang_array2[1,1] = 200

In [34]:
tang_array

array([[  1,   2,   3],
       [  4, 100,   6],
       [  7,   8,   9]])

#### 12、bool索引数组

In [35]:
tang_array = np.arange(0,100,10)

In [36]:
tang_array

array([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [37]:
mask = np.array([1,0,1,0,0,1,1,1,1,0],dtype = bool)

In [38]:
mask

array([ True, False,  True, False, False,  True,  True,  True,  True,
       False])

In [39]:
tang_array[mask]

array([ 0, 20, 50, 60, 70, 80])

In [40]:
random_array = np.random.rand(10)

In [41]:
random_array

array([0.14697663, 0.10476222, 0.09338239, 0.94645789, 0.60705954,
       0.89813006, 0.17886561, 0.24953086, 0.33188893, 0.76875344])

In [42]:
mask = random_array > 0.5

In [43]:
mask

array([False, False, False,  True,  True,  True, False, False, False,
        True])

In [44]:
tang_array[mask]

array([30, 40, 50, 90])

#### 13、数组类型

In [45]:
tang_array = np.array([1,2,3,4,5],dtype = np.float32)

In [46]:
tang_array

array([1., 2., 3., 4., 5.], dtype=float32)

In [47]:
tang_array.dtype

dtype('float32')

In [48]:
tang_array.itemsize

4

In [49]:
tang_array.nbytes

20

In [50]:
tang_array.size

5

In [51]:
tang_array = np.array([1,10,3.5,'string'])

In [52]:
np.asarray(tang_array, dtype = np.object)

C:\Users\Administrator\AppData\Local\Temp\ipykernel_4376\2419498312.py:1: DeprecationWarning: `np.object` is a deprecated alias for the builtin `object`. To silence this warning, use `object` by itself. Doing this will not modify any behavior and is safe. 
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  np.asarray(tang_array, dtype = np.object)


array(['1', '10', '3.5', 'string'], dtype=object)

In [53]:
tang_array

array(['1', '10', '3.5', 'string'], dtype='<U32')