In [1]:
import numpy as np

In [3]:
tang_array = np.array([[1.5, 1.3, 7.5],
                       [5.6, 7.8, 1.2]])

In [5]:
tang_array

array([[1.5, 1.3, 7.5],
       [5.6, 7.8, 1.2]])

In [6]:
np.sort(tang_array)

array([[1.3, 1.5, 7.5],
       [1.2, 5.6, 7.8]])

In [7]:
np.sort(tang_array, axis = 0)

array([[1.5, 1.3, 1.2],
       [5.6, 7.8, 7.5]])

In [8]:
np.argsort(tang_array)

array([[1, 0, 2],
       [2, 0, 1]], dtype=int64)

In [9]:
tang_array = np.linspace(0,10,10)

In [10]:
tang_array

array([ 0.        ,  1.11111111,  2.22222222,  3.33333333,  4.44444444,
        5.55555556,  6.66666667,  7.77777778,  8.88888889, 10.        ])

In [11]:
values = np.array([2.5,6.6,7])

In [12]:
np.searchsorted(tang_array, values)

array([3, 6, 7], dtype=int64)

In [13]:
tang_array = np.array([[1,0,6],[1,7,0],[2,3,1],[2,4,0]])

In [14]:
tang_array

array([[1, 0, 6],
       [1, 7, 0],
       [2, 3, 1],
       [2, 4, 0]])

In [ ]:
index = np.lexsort([ ])