# 运算

In [1]:
import numpy as np

In [5]:
x = np.array([5,5])
y = np.array([2,2])
x

array([5, 5])

In [7]:
y

array([2, 2])

### 1、multiply（）对应元素乘积

In [6]:
np.multiply(x,y)

array([10, 10])

### 2、矩阵的乘法，内积

In [8]:
np.dot(x,y)

20

In [11]:
x.shape = (1,2)
x

array([[5, 5]])

In [13]:
y.shape = (2,1)
y

array([[2],
       [2]])

In [14]:
np.dot(x,y)

array([[20]])

In [15]:
np.dot(y,x)

array([[10, 10],
       [10, 10]])

### 3、矩阵对应位置元素相乘

In [22]:
x = np.array([[1,1,1],[2,2,2]])
y = np.array([[1,5,6], [2,3,4]])

In [23]:
x * y

array([[1, 5, 6],
       [4, 6, 8]])

In [24]:
x==y

array([[ True, False, False],
       [ True, False, False]])

### 4、与、或、非

In [29]:
np.logical_and(x,y)      

array([[False, False, False],
       [False, False, False]])

In [30]:
np.logical_or(x,y)    

array([[ True,  True,  True],
       [ True,  True,  True]])

In [31]:
np.logical_not(x,y)    

array([[0, 0, 0],
       [0, 0, 0]])