# Numpy的随机模块

In [1]:
import numpy as np

#### 1、随机浮点数,默认随机数范围[0,1]

In [2]:
np.random.rand(3,2)

array([[0.7970747 , 0.0955766 ],
       [0.31010943, 0.33705939],
       [0.5687431 , 0.15840771]])

In [3]:
np.random.rand()

0.4118943515978717

In [4]:
np.random.random_sample()

0.8753250184661481

### 2、随机整数，左闭右开，np.random.randint(左闭，右开，size=)

In [5]:
np.random.randint(0,10,size = (5,4))

array([[6, 4, 1, 0],
       [7, 2, 0, 1],
       [7, 7, 9, 3],
       [5, 9, 7, 9],
       [8, 6, 7, 6]])

In [6]:
np.random.randint(0,10,3)

array([9, 4, 1])

### 3、高斯分布

In [7]:
mu, sigma= 0, 0.1

In [8]:
np.random.normal(mu, sigma, 10)

array([ 0.04197255,  0.12634725,  0.0496995 ,  0.13357762,  0.03309946,
       -0.00824288, -0.05967185, -0.10782899, -0.17100911, -0.00761046])

In [10]:
np.random.normal(mu, sigma, 10)

array([ 0.02456,  0.07385,  0.03016, -0.1647 ,  0.01226,  0.22163,
        0.09274,  0.0406 , -0.00421,  0.00473])

### 4、改变精度 np.set_printoptions(precision= )

In [9]:
np.set_printoptions(precision= 5)

### 5、洗牌（打乱顺序）np.random.shuffle()

In [11]:
tang_array = np.arange(10)
tang_array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
np.random.shuffle(tang_array)
tang_array

array([4, 8, 5, 7, 2, 6, 1, 9, 0, 3])

### 6、随机种子,设定好随机种子，后续随机数都是一样的

In [20]:
np.random.seed(0)

In [22]:
np.random.normal(mu, sigma, 10)

array([ 0.0144 ,  0.14543,  0.0761 ,  0.01217,  0.04439,  0.03337,
        0.14941, -0.02052,  0.03131, -0.08541])